# 1. 使用国内加速的 Docker 镜像源
FROM docker.1ms.run/pytorch/pytorch:2.12.1-cuda13.0-cudnn9-runtime

# 2. 设置工作目录
WORKDIR /app

# 3. 设置环境变量
ENV PIP_NO_CACHE_DIR=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

# 5. 配置 pip 全局使用清华源，并安装 Python 依赖
# 使用 -i https://pypi.tuna.tsinghua.edu.cn/simple 极速下载
RUN pip install --upgrade pip -i https://pypi.tuna.tsinghua.edu.cn/simple && \
    pip install -i https://pypi.tuna.tsinghua.edu.cn/simple \
    opencv-python-headless==4.11.0.86 \
    transformers==4.57.1 \
    "numpy<=1.26.0" \
    Pillow==11.1.0 \
    peft \
    torchvision \
    decord==0.6.0 \
    lmdb==1.7.5 \
    fastapi \
    uvicorn \
    python-multipart

# 6. 复制项目代码
# COPY . /app

# 7. 暴露端口
EXPOSE 8000

# 8. 默认启动命令
# CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]